apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentence
spec:
  selector:
      matchLabels:
        app: sentence
  replicas: 1
  template:
    metadata:
      labels:
        app: sentence
    spec:
      containers:
        - name: sentence-service
          image: sentence-service-img
          imagePullPolicy: Never
          ports:
            - containerPort: 8080